### ISSUE TITLE
Servicex Helm chart doesn't allow to use of k8s sealed secrets

### ISSUE THREAD

**Issue by oshadura** [ssl-hep/ServiceX#286]
While adding ServiceX in Flux we found out that Servicex Helm chart doesn't allow to use of k8s sealed secrets:

```
globusClientID:
        valueFrom:
          secretKeyRef:
            name: servicex-globus-auth
            key: globusClientID
```
 and other cases.

cc: @jthiltges 

The Servicex uses an envvar to find the config file, but the chart doesn't let you use your own config. https://github.com/ssl-hep/ServiceX/blob/develop/servicex/templates/app/deployment.yaml#L21-L22

And at the same time, ServiceX application itself only looks at the config file, no envvars. https://github.com/ssl-hep/ServiceX_App/blob/0c9df3029b9e1e157416e239454698a4a0419bc1/servicex/web/utils.py#L5-L7

Trying to use globusClientID from secrets at https://cmsaf-servicex.servicex.coffea.casa/ fails with `client_id must be a valid UUID.`, while Globus UUID is correct.
