### ISSUE TITLE
Don't require ServiceX Code in the transformer container

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#302]
# Story
_As a transform author, I want to write a new transformer that employs an existing experiment's container without having to inject the transformer library into that container so that I can use very old containers to do analysis on data that has been preserved from previous releases of software._

# Assumptions
1. The app creates pods with two containers: The ServiceX driver and the Physics image.
2. The two containers communicate via a shared `emptyDir` volume
3. The ServiceX driver container will write a file-based FIFO queue
4. The Physics container will write the output file to the shared volume along with a semaphore file
5. The ServiceX driver container will wait for Semaphore files and transfer the output file to Minio and signal ServiceX
6. There should not be any python code in the Physics container. The workflow should use Bash and simply invoke the transformer command
7. The Code Generator should be modified to return the command line to be invoked in the physics container.

# Context
This is the result of noticing two things recently when dealing with our transformers:

* When @sthapa was upgrading logging on the ATLAS xAOD Release 20 containers, he was constantly fighting with Python 2 vs Python 3. Eventually, with a good deal of time on his part, he was able to make the logging sections of the logging library work in both cases.
* When @gordonwatts built the CMS Run 1 AOD transformer, it turned out to be against a container image of RHEL6 - which is no longer supported by CERN. It is so unsupported by CERN, in fact, that yum's index of OS package repositories no longer exists on the web, meaning yum is totally broken. Further, the image does not have `pip` installed on it: so it was not possible to install `pip` and thus to properly install the python packages to run the transformer. In the end, I downloaded python 3.8, and thank goodness is builds under gcc 4.X (which IS VERY OLD), and I was able to bootstrap up from there. But since Python 2 and Python 3 now have to co-exist, and I had to do some hacky, but reproducible, things. The solution works, but it is quite fragile.

Both of these things lead me to wonder if there wasn't a better way.

**Comment by gordonwatts** [comment]
A possible approach - which I don't want to add above because I don't know how crazy it is - would be to have a transform manager container that runs configures containers/jobs to run, and each one just processes a single file off of rabbit, but it has to mount the output file, and when the output file is written, it has to be sent to the proper place (minio, etc.).

Or perhaps a container that runs other via docker?

I don't really know what is possible here.

This would be an option for those transformers that can't continuously process messages off the queue - which is obviously much better and more efficient. This mechanism would be here to support legacy containers - which I suspect we will get a few of because of ServiceX's ability to turn legacy data into something modern without too much messy stuff by the end-user (once the transformer is written!!).

**Comment by BenGalewsky** [comment]
Full documentation of Michael's work can be found in the [sidecar container repo](https://github.com/ssl-hep/ServiceX_Sidecar_Transformer)

**Comment by BenGalewsky** [comment]
Changes to the app to setup the pods with the correct sidecar settings can be found in the app's [sidecar branch](https://github.com/ssl-hep/ServiceX_App/tree/sidecar) along with the [Helm Chart Sidecar branch](https://github.com/ssl-hep/ServiceX/tree/sidecar)

**Comment by BenGalewsky** [comment]
I've migrated all of the development to the `sidecar-monorepo` branch of ServiceX Repo.

Gave it a quick check and see a few issues to start with:
1. I don't think the transformer manager is correctly [starting the science container and the sidecar](https://github.com/ssl-hep/ServiceX/blob/bc7c8c09cd408b10360f48589bfe84eca5561fab/servicex_app/servicex/transformer_manager.py#L169)
2. The unit tests for the transformer manager is a bit of a mess. One of the tests is clearly broken. I [marked it to be skipped](https://github.com/ssl-hep/ServiceX/blob/bc7c8c09cd408b10360f48589bfe84eca5561fab/servicex_app/tests/test_transformer_manager.py#L79) for now.. 
3. We need to allow for separate pullPolicy for the sidecar and the science containers

**Comment by BenGalewsky** [comment]
Here's a values.yaml file that should be able to test out this branch
```yaml
noCerts: false
didFinder:
  rucio:
    enabled: true
    tag: develop
    pullPolicy: Always

  CERNOpenData:
    enabled: false

  YT:
    enabled: false
app:
  tag: sidecar-monorepo
  pullPolicy: Always

transformer:
  pullPolicy: Always
  autoscalerEnabled: false
  defaultTransformerTag: sidecar-monorepo
  scienceImage: sslhep/servicex_func_adl_xaod_transformer
  scienceImageTag: sidecar-monorepo

objectStore:
  enabled: true
  publicURL: localhost:9000
  publicClientUseTLS: false

codeGen:
  image: sslhep/servicex_code_gen_atlas_xaod
  tag: develop

rabbitmq:
  auth:
    erlangCookie: mmmmmmmcoookie
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30672


postgres:
    enabled: true

gridAccount: bgalewsk
```
